permalink: /:title.html
highlighter: rouge
exclude: [README.md]

jekyll-press:
  exclude: '' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
