markdown: kramdown
highlighter: rouge
sass:
  style: compressed

gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-50755011-1
google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY

repository: https://github.com/CModelGen/CModelGen
help_url: https://github.com/CModelGen/CModelGen-help

timezone: America/Los_Angeles

defaults:
  -
    scope:
      path: "_docs"
      type: "docs"
    values:
      layout: "docs"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "news_item"


collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /news/:year/:month/:day/:title/
    output: true
  tutorials:
    output: true

name: CModelGen
description: A Verilog to C/C++ Compiler (This site is folked from Jekyll and is under construction)
url: https://cmodelgen.com

twitter:
  username: cmodelgen

logo: /img/cicon.png

gems:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

exclude:
  - .gitignore
  - README.md
