/*
 *      Copyright (c) 2016 CModelGen Project
 *              ALL RIGHTS RESERVED
 *
 *    This source code is free software; you can redistribute it
 *    and/or modify it in source code form under the terms of the GNU
 *    Library General Public License as published by the Free Software
 *    Foundation; either version 2 of the License, or (at your option)
 *    any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Library General Public License for more details.
 *
 *    You should have received a copy of the GNU Library General Public
 *    License along with this program; if not, write to the Free
 *    Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 *    Boston, MA 02110-1301, USA.
 */
#ifndef DATATYPE_H
#define DATATYPE_H

// Verilog standards defined data type related information.

// The Verilog standards require that the minimum max length of identifier 1024 charactors.
#define MAX_LENGTH_IDENTIFIER 1024U

// Datatype "long" has different definitions on 64-bit 64LP (Windows) and 64LLP (Linux) systems.
// However, "int" is always 32-bit, and "long long" is always 64-bit on all supported 32-bit and
// 64-bit targets.

#define DATATYPE_NORMAL_SIZE_32                       32
#define DATATYPE_NORMAL_NUMBER_OF_BYTES_32            4
#define DATATYPE_NORMAL_SUFFIX_SIGNED_32              ""
#define DATATYPE_NORMAL_SUFFIX_UNSIGNED_32            "U"
#define DATATYPE_NORMAL_NAME_SIGNED_32                PLI_INT32
#define DATATYPE_NORMAL_NAME_UNSIGNED_32              PLI_UINT32
#define DATATYPE_NORMAL_ZERO_SIGNED_32                0
#define DATATYPE_NORMAL_ZERO_UNSIGNED_32              0U
#define DATATYPE_NORMAL_ONE_SIGNED_32                 1
#define DATATYPE_NORMAL_ONE_UNSIGNED_32               1U
#define DATATYPE_NORMAL_ALLONE_SIGNED_32              0xFFFFFFFF
#define DATATYPE_NORMAL_ALLONE_UNSIGNED_32            0xFFFFFFFFU

#define DATATYPE_WIDE_SIZE_32                         64
#define DATATYPE_WIDE_NUMBER_OF_BYTES_32              8
#define DATATYPE_WIDE_SUFFIX_SIGNED_32                "LL"
#define DATATYPE_WIDE_SUFFIX_UNSIGNED_32              "ULL"
#define DATATYPE_WIDE_NAME_SIGNED_32                  PLI_INT64
#define DATATYPE_WIDE_NAME_UNSIGNED_32                PLI_UINT64
#define DATATYPE_WIDE_ZERO_SIGNED_32                  0LL
#define DATATYPE_WIDE_ZERO_UNSIGNED_32                0ULL
#define DATATYPE_WIDE_ONE_SIGNED_32                   1LL
#define DATATYPE_WIDE_ONE_UNSIGNED_32                 1ULL
#define DATATYPE_WIDE_ALLONE_SIGNED_32                0xFFFFFFFFFFFFFFFFLL
#define DATATYPE_WIDE_ALLONE_UNSIGNED_32              0xFFFFFFFFFFFFFFFFULL

#define DATATYPE_ARRAY_SIZE_32                        32
#define DATATYPE_ARRAY_SUFFIX_SIGNED_32               ""
#define DATATYPE_ARRAY_SUFFIX_UNSIGNED_32             "U"
#define DATATYPE_ARRAY_NAME_SIGNED_32                 PLI_INT32
#define DATATYPE_ARRAY_NAME_UNSIGNED_32               PLI_UINT32
#define DATATYPE_ARRAY_ZERO_SIGNED_32                 0
#define DATATYPE_ARRAY_ZERO_UNSIGNED_32               0U
#define DATATYPE_ARRAY_ONE_SIGNED_32                  1
#define DATATYPE_ARRAY_ONE_UNSIGNED_32                1U
#define DATATYPE_ARRAY_ALLONE_SIGNED_32               0xFFFFFFFF
#define DATATYPE_ARRAY_ALLONE_UNSIGNED_32             0xFFFFFFFFU
#define DATATYPE_ARRAY_ORDER_OF_WIDTH_OF_ELEMENT_32   5
#define DATATYPE_ARRAY_NUMBER_OF_ELEMENTS_32(WIDTH)   ( ( (WIDTH) + 31) >> 5)
#define DATATYPE_ARRAY_NUMBER_OF_BYTES_32(WIDTH)      (DATATYPE_ARRAY_NUMBER_OF_ELEMENTS_32(WIDTH) << 2)
#define DATATYPE_ARRAY_BYTES_PER_ELEMENT_32(ELEMENTS) ( (ELEMENTS) << 2)

#define DATATYPE_NORMAL_SIZE_64                       32
#define DATATYPE_NORMAL_NUMBER_OF_BYTES_64            4
#define DATATYPE_NORMAL_SUFFIX_SIGNED_64              ""
#define DATATYPE_NORMAL_SUFFIX_UNSIGNED_64            "U"
#define DATATYPE_NORMAL_NAME_SIGNED_64                PLI_INT32
#define DATATYPE_NORMAL_NAME_UNSIGNED_64              PLI_UINT32
#define DATATYPE_NORMAL_ZERO_SIGNED_64                0
#define DATATYPE_NORMAL_ZERO_UNSIGNED_64              0U
#define DATATYPE_NORMAL_ONE_SIGNED_64                 1
#define DATATYPE_NORMAL_ONE_UNSIGNED_64               1U
#define DATATYPE_NORMAL_ALLONE_SIGNED_64              0xFFFFFFFF
#define DATATYPE_NORMAL_ALLONE_UNSIGNED_64            0xFFFFFFFFU

#define DATATYPE_WIDE_SIZE_64                         64
#define DATATYPE_WIDE_NUMBER_OF_BYTES_64              8
#define DATATYPE_WIDE_SUFFIX_SIGNED_64                "LL"
#define DATATYPE_WIDE_SUFFIX_UNSIGNED_64              "ULL"
#define DATATYPE_WIDE_NAME_SIGNED_64                  PLI_INT64
#define DATATYPE_WIDE_NAME_UNSIGNED_64                PLI_UINT64
#define DATATYPE_WIDE_ZERO_SIGNED_64                  0LL
#define DATATYPE_WIDE_ZERO_UNSIGNED_64                0ULL
#define DATATYPE_WIDE_ONE_SIGNED_64                   1LL
#define DATATYPE_WIDE_ONE_UNSIGNED_64                 1ULL
#define DATATYPE_WIDE_ALLONE_SIGNED_64                0xFFFFFFFFFFFFFFFFLL
#define DATATYPE_WIDE_ALLONE_UNSIGNED_64              0xFFFFFFFFFFFFFFFFULL

#define DATATYPE_ARRAY_SIZE_64                        64
#define DATATYPE_ARRAY_SUFFIX_SIGNED_64               "LL"
#define DATATYPE_ARRAY_SUFFIX_UNSIGNED_64             "ULL"
#define DATATYPE_ARRAY_NAME_SIGNED_64                 PLI_INT64
#define DATATYPE_ARRAY_NAME_UNSIGNED_64               PLI_UINT64
#define DATATYPE_ARRAY_ZERO_SIGNED_64                 0LL
#define DATATYPE_ARRAY_ZERO_UNSIGNED_64               0ULL
#define DATATYPE_ARRAY_ONE_SIGNED_64                  1LL
#define DATATYPE_ARRAY_ONE_UNSIGNED_64                1ULL
#define DATATYPE_ARRAY_ALLONE_SIGNED_64               0xFFFFFFFFFFFFFFFFLL
#define DATATYPE_ARRAY_ALLONE_UNSIGNED_64             0xFFFFFFFFFFFFFFFFULL
#define DATATYPE_ARRAY_ORDER_OF_WIDTH_OF_ELEMENT_64   6
#define DATATYPE_ARRAY_NUMBER_OF_ELEMENTS_64(WIDTH)   ( ( (WIDTH) + 63) >> 6)
#define DATATYPE_ARRAY_NUMBER_OF_BYTES_64(WIDTH)      (DATATYPE_ARRAY_NUMBER_OF_ELEMENTS_64(WIDTH) << 3)
#define DATATYPE_ARRAY_BYTES_PER_ELEMENT_64(ELEMENTS) ( (ELEMENTS) << 3)

#ifdef CMODELGEN_64

#define DATATYPE_NORMAL_SIZE                          DATATYPE_NORMAL_SIZE_64
#define DATATYPE_NORMAL_NUMBER_OF_BYTES               DATATYPE_NORMAL_NUMBER_OF_BYTES_64
#define DATATYPE_NORMAL_SUFFIX_SIGNED                 DATATYPE_NORMAL_SUFFIX_SIGNED_64
#define DATATYPE_NORMAL_SUFFIX_UNSIGNED               DATATYPE_NORMAL_SUFFIX_UNSIGNED_64
#define DATATYPE_NORMAL_NAME_SIGNED                   DATATYPE_NORMAL_NAME_SIGNED_64
#define DATATYPE_NORMAL_NAME_UNSIGNED                 DATATYPE_NORMAL_NAME_UNSIGNED_64
#define DATATYPE_NORMAL_ZERO_SIGNED                   DATATYPE_NORMAL_ZERO_SIGNED_64
#define DATATYPE_NORMAL_ZERO_UNSIGNED                 DATATYPE_NORMAL_ZERO_UNSIGNED_64
#define DATATYPE_NORMAL_ONE_SIGNED                    DATATYPE_NORMAL_ONE_SIGNED_64
#define DATATYPE_NORMAL_ONE_UNSIGNED                  DATATYPE_NORMAL_ONE_UNSIGNED_64
#define DATATYPE_NORMAL_ALLONE_SIGNED                 DATATYPE_NORMAL_ALLONE_SIGNED_64
#define DATATYPE_NORMAL_ALLONE_UNSIGNED               DATATYPE_NORMAL_ALLONE_UNSIGNED_64

#define DATATYPE_WIDE_SIZE                            DATATYPE_WIDE_SIZE_64
#define DATATYPE_WIDE_NUMBER_OF_BYTES                 DATATYPE_WIDE_NUMBER_OF_BYTES_64
#define DATATYPE_WIDE_SUFFIX_SIGNED                   DATATYPE_WIDE_SUFFIX_SIGNED_64
#define DATATYPE_WIDE_SUFFIX_UNSIGNED                 DATATYPE_WIDE_SUFFIX_UNSIGNED_64
#define DATATYPE_WIDE_NAME_SIGNED                     DATATYPE_WIDE_NAME_SIGNED_64
#define DATATYPE_WIDE_NAME_UNSIGNED                   DATATYPE_WIDE_NAME_UNSIGNED_64
#define DATATYPE_WIDE_ZERO_SIGNED                     DATATYPE_WIDE_ZERO_SIGNED_64
#define DATATYPE_WIDE_ZERO_UNSIGNED                   DATATYPE_WIDE_ZERO_UNSIGNED_64
#define DATATYPE_WIDE_ONE_SIGNED                      DATATYPE_WIDE_ONE_SIGNED_64
#define DATATYPE_WIDE_ONE_UNSIGNED                    DATATYPE_WIDE_ONE_UNSIGNED_64
#define DATATYPE_WIDE_ALLONE_SIGNED                   DATATYPE_WIDE_ALLONE_SIGNED_64
#define DATATYPE_WIDE_ALLONE_UNSIGNED                 DATATYPE_WIDE_ALLONE_UNSIGNED_64

#define DATATYPE_ARRAY_SIZE                           DATATYPE_ARRAY_SIZE_64
#define DATATYPE_ARRAY_SUFFIX_SIGNED                  DATATYPE_ARRAY_SUFFIX_SIGNED_64
#define DATATYPE_ARRAY_SUFFIX_UNSIGNED                DATATYPE_ARRAY_SUFFIX_UNSIGNED_64
#define DATATYPE_ARRAY_NAME_SIGNED                    DATATYPE_ARRAY_NAME_SIGNED_64
#define DATATYPE_ARRAY_NAME_UNSIGNED                  DATATYPE_ARRAY_NAME_UNSIGNED_64
#define DATATYPE_ARRAY_ZERO_SIGNED                    DATATYPE_ARRAY_ZERO_SIGNED_64
#define DATATYPE_ARRAY_ZERO_UNSIGNED                  DATATYPE_ARRAY_ZERO_UNSIGNED_64
#define DATATYPE_ARRAY_ONE_SIGNED                     DATATYPE_ARRAY_ONE_SIGNED_64
#define DATATYPE_ARRAY_ONE_UNSIGNED                   DATATYPE_ARRAY_ONE_UNSIGNED_64
#define DATATYPE_ARRAY_ALLONE_SIGNED                  DATATYPE_ARRAY_ALLONE_SIGNED_64
#define DATATYPE_ARRAY_ALLONE_UNSIGNED                DATATYPE_ARRAY_ALLONE_UNSIGNED_64
#define DATATYPE_ARRAY_ORDER_OF_WIDTH_OF_ELEMENT      DATATYPE_ARRAY_ORDER_OF_WIDTH_OF_ELEMENT_64
#define DATATYPE_ARRAY_NUMBER_OF_ELEMENTS(WIDTH)      DATATYPE_ARRAY_NUMBER_OF_ELEMENTS_64(WIDTH)
#define DATATYPE_ARRAY_NUMBER_OF_BYTES(WIDTH)         DATATYPE_ARRAY_NUMBER_OF_BYTES_64(WIDTH)
#define DATATYPE_ARRAY_BYTES_PER_ELEMENT(ELEMENTS)    DATATYPE_ARRAY_BYTES_PER_ELEMENT_64(ELEMENTS)

#else

#define DATATYPE_NORMAL_SIZE                          DATATYPE_NORMAL_SIZE_32
#define DATATYPE_NORMAL_NUMBER_OF_BYTES               DATATYPE_NORMAL_NUMBER_OF_BYTES_32
#define DATATYPE_NORMAL_SUFFIX_SIGNED                 DATATYPE_NORMAL_SUFFIX_SIGNED_32
#define DATATYPE_NORMAL_SUFFIX_UNSIGNED               DATATYPE_NORMAL_SUFFIX_UNSIGNED_32
#define DATATYPE_NORMAL_NAME_SIGNED                   DATATYPE_NORMAL_NAME_SIGNED_32
#define DATATYPE_NORMAL_NAME_UNSIGNED                 DATATYPE_NORMAL_NAME_UNSIGNED_32
#define DATATYPE_NORMAL_ZERO_SIGNED                   DATATYPE_NORMAL_ZERO_SIGNED_32
#define DATATYPE_NORMAL_ZERO_UNSIGNED                 DATATYPE_NORMAL_ZERO_UNSIGNED_32
#define DATATYPE_NORMAL_ONE_SIGNED                    DATATYPE_NORMAL_ONE_SIGNED_32
#define DATATYPE_NORMAL_ONE_UNSIGNED                  DATATYPE_NORMAL_ONE_UNSIGNED_32
#define DATATYPE_NORMAL_ALLONE_SIGNED                 DATATYPE_NORMAL_ALLONE_SIGNED_32
#define DATATYPE_NORMAL_ALLONE_UNSIGNED               DATATYPE_NORMAL_ALLONE_UNSIGNED_32

#define DATATYPE_WIDE_SIZE                            DATATYPE_WIDE_SIZE_32
#define DATATYPE_WIDE_NUMBER_OF_BYTES                 DATATYPE_WIDE_NUMBER_OF_BYTES_32
#define DATATYPE_WIDE_SUFFIX_SIGNED                   DATATYPE_WIDE_SUFFIX_SIGNED_32
#define DATATYPE_WIDE_SUFFIX_UNSIGNED                 DATATYPE_WIDE_SUFFIX_UNSIGNED_32
#define DATATYPE_WIDE_NAME_SIGNED                     DATATYPE_WIDE_NAME_SIGNED_32
#define DATATYPE_WIDE_NAME_UNSIGNED                   DATATYPE_WIDE_NAME_UNSIGNED_32
#define DATATYPE_WIDE_ZERO_SIGNED                     DATATYPE_WIDE_ZERO_SIGNED_32
#define DATATYPE_WIDE_ZERO_UNSIGNED                   DATATYPE_WIDE_ZERO_UNSIGNED_32
#define DATATYPE_WIDE_ONE_SIGNED                      DATATYPE_WIDE_ONE_SIGNED_32
#define DATATYPE_WIDE_ONE_UNSIGNED                    DATATYPE_WIDE_ONE_UNSIGNED_32
#define DATATYPE_WIDE_ALLONE_SIGNED                   DATATYPE_WIDE_ALLONE_SIGNED_32
#define DATATYPE_WIDE_ALLONE_UNSIGNED                 DATATYPE_WIDE_ALLONE_UNSIGNED_32

#define DATATYPE_ARRAY_SIZE                           DATATYPE_ARRAY_SIZE_32
#define DATATYPE_ARRAY_SUFFIX_SIGNED                  DATATYPE_ARRAY_SUFFIX_SIGNED_32
#define DATATYPE_ARRAY_SUFFIX_UNSIGNED                DATATYPE_ARRAY_SUFFIX_UNSIGNED_32
#define DATATYPE_ARRAY_NAME_SIGNED                    DATATYPE_ARRAY_NAME_SIGNED_32
#define DATATYPE_ARRAY_NAME_UNSIGNED                  DATATYPE_ARRAY_NAME_UNSIGNED_32
#define DATATYPE_ARRAY_ZERO_SIGNED                    DATATYPE_ARRAY_ZERO_SIGNED_32
#define DATATYPE_ARRAY_ZERO_UNSIGNED                  DATATYPE_ARRAY_ZERO_UNSIGNED_32
#define DATATYPE_ARRAY_ONE_SIGNED                     DATATYPE_ARRAY_ONE_SIGNED_32
#define DATATYPE_ARRAY_ONE_UNSIGNED                   DATATYPE_ARRAY_ONE_UNSIGNED_32
#define DATATYPE_ARRAY_ALLONE_SIGNED                  DATATYPE_ARRAY_ALLONE_SIGNED_32
#define DATATYPE_ARRAY_ALLONE_UNSIGNED                DATATYPE_ARRAY_ALLONE_UNSIGNED_32
#define DATATYPE_ARRAY_ORDER_OF_WIDTH_OF_ELEMENT      DATATYPE_ARRAY_ORDER_OF_WIDTH_OF_ELEMENT_32
#define DATATYPE_ARRAY_NUMBER_OF_ELEMENTS(WIDTH)      DATATYPE_ARRAY_NUMBER_OF_ELEMENTS_32(WIDTH)
#define DATATYPE_ARRAY_NUMBER_OF_BYTES(WIDTH)         DATATYPE_ARRAY_NUMBER_OF_BYTES_32(WIDTH)
#define DATATYPE_ARRAY_BYTES_PER_ELEMENT(ELEMENTS)    DATATYPE_ARRAY_BYTES_PER_ELEMENT_32(ELEMENTS)

#endif

#define DATATYPE_NUMBER_OF_BYTES(WIDTH)                                  \
( ( (WIDTH) <= DATATYPE_NORMAL_SIZE) ? DATATYPE_NORMAL_NUMBER_OF_BYTES : \
  ( (WIDTH) <= DATATYPE_WIDE_SIZE)   ? DATATYPE_WIDE_NUMBER_OF_BYTES   : \
  DATATYPE_ARRAY_NUMBER_OF_BYTES(WIDTH) )

/* Properties has the following bits:                           */
/* [31..16   ]                                                  */
/* [Width - 1]                                                  */
/* [15        ] [14      ][13      ] [12..2               ]     */
/* [Signedness] [Reserved][Reserved] [Number of bytes >> 2]     */
/* [1           ] [0            ]                               */
/* [Read protect] [Write protect]                               */

/* Construct properties */
#define MGL_MAKE_PROPERTIES(SIGNED,WIDTH)                                \
  ( ( ( (WIDTH) - 1) << 16) | ( (SIGNED) ? (1 << 15) : 0) |              \
    (DATATYPE_NUMBER_OF_BYTES(WIDTH) ) )
/* Take signed out of properties */
#define MGL_SIGNED(PROPERTIES) ( ( (PROPERTIES) >> 15) & 0x1)
/* Take number of bytes out of properties */
#define MGL_NOB(PROPERTIES) ( (PROPERTIES) & 0x1FFC)
/* Take width out of properties */
#define MGL_WIDTH(PROPERTIES) ( ( (PROPERTIES) >> 16) + 1)
/* The read protect bit */
#define MGL_READPROTECT_BIT 0x2
/* Read the read protect bit */
#define MGL_IS_READPROTECT(PROPERTIES) ( (PROPERTIES) & MGL_READPROTECT_BIT)
/* The write protect bit */
#define MGL_WRITEPROTECT_BIT 0x1
/* Read the write protect bit */
#define MGL_IS_WRITEPROTECT(PROPERTIES) ( (PROPERTIES) & MGL_WRITEPROTECT_BIT)

#endif // DATATYPE_H
